### ISSUE TITLE
Change APK package name

### ISSUE THREAD

**Issue by omkar-tenkale** [kellinwood/zip-signer#5]
Dumb question

But is it possible for zip-signer to modify the APK package name

Maybe by editing AndroidManifest.xml file's package="com.mypkg" property?

I tried signing a recompressed zip apk with zip-signer and installing it

It worked when i only modified raw file
But i got apk parse error when i edited the Manifest file ( to change pkg name ) in the same process

https://stackoverflow.com/questions/66753199/editing-manifest-to-change-package-name-fails-even-after-signing

**Comment by kellinwood** [comment]
It's been too long since I've been active with Android development, so I don't know.   XML files get converted to binary format by the Android toolchain in some cases, so editing them may not work for that reason, or maybe the change in package name has to match a change to the package hierarchy in the app's source code.  I'm just guessing at this point, sorry.

**Comment by omkar-tenkale** [comment]
I'll explore more on this
Thanks for this wonderful lib 😍
